In [6]:
import numpy as np

# create numpy array of letters a-j
letter_array = np.array(['a','b','c','d','e','f','g','h','i','j'])
print("Letter Array: ", letter_array)



Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']


In [5]:
letter_array.dtype.name

'str32'

In [3]:
letter_array.shape

(10,)

In [4]:
letter_array.size

10

In [13]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,33,2).reshape(4,4)
X


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [16]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)

# Use Boolean indexing to pick out only the odd numbers in the array

Y = X[X%2==1]
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
Y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [48]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

a = np.arange(4)
b= np.array([1,1,1,1])
x = a[:,np.newaxis] + b
np.transpose(x)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [22]:
import pandas as pd

# Create a Pandas Series that contains the distance of some planets from the Sun.
# Use the name of the planets as the index to your Pandas Series, and the distance
# from the Sun as your data. The distance from the Sun is in units of 10^6 km

distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]

planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

In [25]:
# Create a Pandas Series using the above data, with the name of the planets as
# the index and the distance from the Sun as your data.
dist_planets = pd.Series(data=distance_from_sun, index=planets)
dist_planets

Earth       149.6
Saturn     1433.5
Mars        227.9
Venus       108.2
Jupiter     778.6
dtype: float64

In [69]:
# Calculate the number of minutes it takes sunlight to reach each planet. You can
# do this by dividing the distance from the Sun for each planet by the speed of light.
# Since in the data above the distance from the Sun is in units of 10^6 km, you can
# use a value for the speed of light of c = 18, since light travels 18 x 10^6 km/minute.
a = pd.Series(distance_from_sun)
time_light = a / 18
time_light

0     8.3
1    79.6
2    12.7
3     6.0
4    43.3
dtype: float64

In [70]:
# Use Boolean indexing to select only those planets for which sunlight takes less
# than 40 minutes to reach them.
close_planets = time_light[time_light<40]
close_planets

0     8.3
2    12.7
3     6.0
dtype: float64

In [28]:
import pandas as pd
import numpy as np

# Since we will be working with ratings, we will set the precision of our 
# dataframes to one decimal place.
pd.set_option('precision', 1)

# Create a Pandas DataFrame that contains the ratings some users have given to a
# series of books. The ratings given are in the range from 1 to 5, with 5 being
# the best score. The names of the books, the authors, and the ratings of each user
# are given below:

books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])

user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])

In [62]:
# Create a dictionary with the data given above
data = {'Books':books, 'Authors':authors, 'User 1':user_1, 'User 2':user_2, 'User 3':user_3, 'User 4':user_4}

In [63]:
# Use the dictionary to create a Pandas DataFrame
book_ratings = pd.DataFrame(data)
book_ratings

Books              Authors  User 1  User 2  User 3  User 4
0   Great Expectations      Charles Dickens     3.2     5.0     2.0     4.0
1      Of Mice and Men       John Steinbeck     NaN     1.3     2.3     3.5
2     Romeo and Juliet  William Shakespeare     2.5     4.0     NaN     4.0
3     The Time Machine          H. G. Wells     NaN     3.8     4.0     5.0
4  Alice in Wonderland        Lewis Carroll     NaN     NaN     NaN     4.2

In [66]:
# If you created the dictionary correctly you should have a Pandas DataFrame
# that has column labels: 'Author', 'Book Title', 'User 1', 'User 2', 'User 3',
# 'User 4' and row indices 0 through 4.

# Now replace all the NaN values in your DataFrame with the average rating in
# each column. Replace the NaN values in place. HINT: you can use the fillna()
# function with the keyword inplace = True, to do this. Write your code below:
book_ratings.fillna(book_ratings.mean(), inplace=True)
